### ISSUE TITLE
Is the repo accepting PRs?

### ISSUE THREAD

**Issue by irfanzainudin** [goodmami/rumi-jawi#8]
# Introduction

Hi there, I'm Irfan and I'm building a pantun database called Pantunis which is live at [pantunis.com](https://www.pantunis.com/). I want to convert the Malay pantuns from Rumi to Jawi and I stumbled upon your Rumi-to-Jawi converter.

Thank you for the incredible work you've done on the converter which allowed me to convert most of the Malay pantuns.

However, there are gaps in the dictionary and I'm working on filling those gaps.

## Approach

I speak Malay natively and learnt Jawi from a young age.

My approach would be to follow the existing spelling because most of the gaps (so far) has been alternate Rumi spellings, suffixes and prefixes (imbuhan). Example below:

```txt
...
بربوک ڤواسا برسام راکن،
راکن يڠ لاما ڤرݢي ملات،
Ramadhan سميمڠڽ سبواه ڤنديديقن،
مڠوجي کأخلاصن کڤد يڠ ممينتا
===
Sebarkan کباءيقن تق کيرا سياڤا،
هاروس disantuni سموا انسان،
اڤ ڤون قرينه ايبو دان باڤ،
Layani دڠن ڤنوه کأخلاصن
===
...
```

I'm still working on the corpus, but I wanted to save my progress on Github and was wondering if you're accepting PRs for the repo.

Thank you!

**Comment by goodmami** [comment]
Hi @irfanzainudin, thanks for your interest in this project! Technically, yes, I will accept PRs, but unfortunately I have not had much time to work on this recently, so I can't promise to be very responsive. I would, however, be very happy to have a potential collaborator who has knowledge of Malay and Jawi (as I'm not very proficient in either).

And your pantun database sounds very interesting. It would be great if this dictionary could help support your website; similarly, this dictionary could benefit from the additional words in the pantuns that you could identify as missing.

**Comment by irfanzainudin** [comment]
Hi @goodmami, I am very happy to collaborate on the dictionary :)

Let me know what I have to do.

Thanks!

**Comment by goodmami** [comment]
Thanks, @irfanzainudin. I should write up a `CONTRIBUTING.md` file, but for now:

- It's best if PRs tackle one issue, although there may be many corrections in the PR for that issue
- If the issue the PR addresses is a bug or problem in the dictionary, it's best to first have an issue describing the problem, then the PR provides the fix. This helps to create a clear record of work done.
- If the PR is merely adding missing words, an issue is not necessary. It would help to explain in the PR how the missing words were identified (e.g., from a pantun).

I look forward to any contributions you might make!
